import RuneTableType from "./runetable.type";

export const oldRunes: RuneTableType = {
    name: "Old Runes",
    chars: [
        ["th"],
        ["a"],
        ["b"],
        ["c"],
        ["d"],
        ["e"],
        ["f"],
        ["g"],
        ["h"],
        ["i"],
        ["j"],
        ["l"],
        ["m"],
        ["n"],
        ["o"],
        ["k", "o"],
        ["p"],
        ["r"],
        ["s"],
        ["t"],
        ["u", "v"],
        ["w"],
        ["x", "z"],
        ["y", "æ"],
    ],
    runes: [
        "ᚦ",
        "ᚨ",
        "ᛒ",
        "ᚲ",
        "ᛞ",
        "ᛖ",
        "ᚠ",
        "ᚷ",
        "ᚺ",
        "ᛁ",
        "ᛃ",
        "ᛚ",
        "ᛗ",
        "ᚾ",
        "ᛟ",
        "ᚴ",
        "ᛈ",
        "ᚱ",
        "ᛋ",
        "ᛏ",
        "ᚢ",
        "ᚹ",
        "ᛉ",
        "ᛇ",
    ],
};
