import RuneTableType from "./runetable.type";

export const newRunes: RuneTableType = {
    name: "New Runes",
    chars: [
        ["th"],
        ["a"],
        ["b"],
        ["c"],
        ["k", "q"],
        ["d"],
        ["e"],
        ["f"],
        ["g"],
        ["h"],
        ["i"],
        ["j"],
        ["l"],
        ["m"],
        ["n"],
        ["o"],
        ["p"],
        ["r"],
        ["s"],
        ["t"],
        ["u"],
        ["v"],
        ["w"],
        ["x", "z"],
        ["y"],
    ],
    runes: [
        "ᚦ",
        "ᚨ",
        "ᛒ",
        "ᛊ",
        "ᚲ",
        "ᛞ",
        "ᛖ",
        "ᚠ",
        "ᚷ",
        "ᚺ",
        "ᛇ",
        "ᛃ",
        "ᛚ",
        "ᛗ",
        "ᚾ",
        "ᛟ",
        "ᛈ",
        "ᚱ",
        "ᛋ",
        "ᛏ",
        "ᚢ",
        "ᚡ",
        "ᚹ",
        "ᛉ",
        "ᛁ",
    ],
};

// ᚨᛒᛊᚲᛞᛖᚠᚷᚺᛇᛃᛚᛗᚾᛟᛈᚱᛋᛏᚢᚡᚹᛉᛁᚦ
// ᚨ-A  ᛒ-B  ᛊ-C  ᚲ-K/Q  ᛞ-D  ᛖ-E  ᚠ-F  ᚷ-G  ᚺ-H  ᛇ-I  ᛃ-J  ᛚ-L  ᛗ-M  ᚾ-N  ᛟ-O  ᛈ-P  ᚱ-R  ᛋ-S  ᛏ-T  ᚢ-U  ᚡ-V  ᚹ-W  ᛉ-X/Z  ᛁ-Y  ᚦ-Th
